### ISSUE TITLE
do we still need nbzip and nbgitpuller?

### ISSUE THREAD

**Issue by kcranston** [earthlab/hub-ops#160]
Updating the ea-hub, and wanting to know if we still need nbzip and nbgitpuller. I don't have these installed in the nbgrader hub we used for the bootcamp test. We can always add them back later - just trying for a simple-as-possible initial build.

**Comment by lwasser** [comment]
@kcranston i know in this case you did want to move forward but i think in the future let's talk about removing things before doing it. i really didn't want this removed from the hub.

i'm doing some cleanup now and adding it back. see https://github.com/earthlab/hub-ops/pull/172

**Comment by lwasser** [comment]
i'm not sure if nbgitpuller is documented but it's discussed here. note to add this to the docs at some point!! @jlpalomino this might be something you could do as it would be helpful for you to know how it works as well!! 

https://github.com/earthlab/hub-ops/issues/49

**Comment by kcranston** [comment]
> @kcranston i know in this case you did want to move forward but i think in the future let's talk about removing things before doing it. i really didn't want this removed from the hub.
> 
Absolutely! You are right that in this case, I wanted to make sure we had a functional hub for this week and also wanted to keep things as simple as possible.

**Comment by kcranston** [comment]
PR #172 adds nbgitpuller back but not nbzip. Looking through the nbgitpuller code, I don't see any evidence that it requires nbzip.

**Comment by lwasser** [comment]
totally. 

https://github.com/jupyterhub/nbgitpuller/blob/master/setup.py#L22 
doesn't look like it's even a dep and i just lanuched the hub and it worked!!
 
@jlpalomino a few notes on this: see image below. Any student who has logged in since that PR merge will see two folders now. homework-templates is one we can delete. it isn't a lot of students but we might just want to clean that up for them. that dir is there because of the merge happening before we updated the repo link. 

<img width="1271" alt="Screen Shot 2019-09-03 at 11 01 24 AM" src="https://user-images.githubusercontent.com/7649194/64193627-5fab5600-ce3a-11e9-89b1-14ae7f1d9c09.png">

Another item to test jenny. In theory the way this works is that files that a student has modified should NOT be updated by nbgitpuller. because i hadn't tested that in the past, i've always told them to place their modified notebooks in a different location.  let's work together to figure out what the ideal scenario is for this class and then we can update the docs accordingly. should we create a new issue surrounding this particular item (testing nbgitpuller and student workflows in the hub?)

**Comment by lwasser** [comment]
closing this an di'll open a new issue to document how we use nbzip and gitpuller
