### ISSUE TITLE
Deleted user files still exist after a student is deleted from the hub

### ISSUE THREAD

**Issue by nkorinek** [earthlab/hub-ops#185]
I took the class a year ago and was deleted from the hub. When I was added back to the hub recently, my files were still stored there. This means the files are being stored somewhere.

**Comment by lwasser** [comment]
thanks @nkorinek @kcranston this is the issue i was talking about the other day. essentially a student who is deleted technically from the hub still has storage space on google cloud. i would imagine we are paying for that space. i'd like to remove the storage when we remove a student. i'd also like to know how removing them from the yaml config file differs from the admin section that you can access when you are in the hub? the admin section in the hub doesn't seem to do what i would think it should do.

**Comment by kcranston** [comment]
Deleting a user from the yaml only removes their ability to authenticate to the hub. We need to delete the old volumes manually using `kubectl` or the GCloud console. Best practice would be to shutdown the hub at the end of each course [following these instructions](https://earthlab-hub-ops.readthedocs.io/en/latest/day-to-day.html#removing-a-hub), which would remove the storage. 

Here are the [JupyterHub docs about storage](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html), which does describe manually deleting pods / storage. 

If we wanted to keep the hub running between courses / use the same hub for multiple courses, we could probably automate the deletion because the pod name / persistent volume name contains the username.

**Comment by lwasser** [comment]
thanks @kcranston !! so since the ea hub has been running for a year, that means we have storage for all of the students that we are paying for currently. Can we go in and look at how many pods are active in the background there? IE pods for students we've deleted but have storage still? perhaps you can show this to us on wednesday or we could run through it together just so i understand how it works! ? 

shutting down the hub does make a lot of sense. but if we use the same hub for the fall and spring (which i think we will) we will want to keep it running for just the students that are in the professional program an continuing on to the next course. 

this is super helpful!!

**Comment by lwasser** [comment]
i want to note that in those docs it says 

> When a user shuts down their server, their user pod is deleted and their volume is detached from the pod, but the PVC and PV objects still exist. In the future, when the user logs back in, JupyterHub will detect that the user has a pre-existing PVC and will simply attach it to their new pod, rather than creating a new PVC.

So i'm not convinced that even shutting down the hub will delete ALL storage UNLESS the docs -- that one CLI argument does actually delete all storage? it would be really good to clarify how storage works AND also i still have this #205 issue where a pod can fill up and crash -- we need a way to manage storage.

**Comment by kcranston** [comment]
You are correct - shutting down the hub does not delete the persistent volumes. We would need to do that manually. Agree completely that we want a better process for end-of-course cleanup.

**Comment by kcranston** [comment]
The [z2jh docs](https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-storage.html) are pretty explicit about deleting volumes:

> PersistentVolumeClaims and PersistentVolumes are not deleted unless the PersistentVolumeClaim is explicitly deleted by the JupyterHub administrator. When a user shuts down their server, their user pod is deleted and their volume is detached from the pod, but the PVC and PV objects still exist. In the future, when the user logs back in, JupyterHub will detect that the user has a pre-existing PVC and will simply attach it to their new pod, rather than creating a new PVC.

**Comment by lwasser** [comment]
ok this makes so much sense @kcranston .. even just documenting this more clearly is helpful. i know how to manually get into the cloud and delete PV's one by one. that is easy but also easy to delete something i shouldn't. i did it via the GUI not CLI however. it would be really great to have a better documented process!! i also couldn't find where i specify the PV size in our yaml files. i found it once in the monitoring folder but that doesn't seem like the right spot for each hub designation.

**Comment by lwasser** [comment]
ok.. so i have an open issue #224 that addresses this. the answer is that a pod's storage will exist UNLESS we run a local command (or go into the google console) and actually delete the pod. So after each class we should consider shutting down the hub and fully deleting all of the pods. I've cleaned up the docs to nclude that section more clearly as a step in the shut down process!
This will be better documented in 224 as well with other associated storage issues!! closing.
