### ISSUE TITLE
What does the admin panel actually do? 

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#216]
i see here #132  that tim was beginning to explore how to "clean up" a hub. Currently when you remove users from the admin interface i'm not sure what it actually does. This is because the names are still in the yaml file. 

Specifically questions
1. When you "delete" a user in the hub admin interface what actually happens on the back end (if anything)
2. When you shut down the hub in the admin interface what happens on the back end?

I would expect that when you delete a user the storage is also removed but that is not the case. it would be good to understand what the admin panel does in the hub and document that. Then document how to safely remove a user and clean up associated storage.

Finally -- i want to understand how much storage costs a month so we can better spec out hubs.

**Comment by betatim** [comment]
The admin panel of a JupyterHub is designed for "all" the ways in which you can deploy a hub. This means some of the buttons in it make more/less sense when your hub is deployed on kubernetes.

For example deleting a user will remove them from the hubs internal DB, but because a Hub in general doesn't need to run on kubernetes it doesn't clean up the storage associated with a user.

Similarly clicking "shutdown" stops the jupyterhub process. WHich if you are just runnign it on a virtual machine does the right thing. If the hub is deployed on kubernetes it will still shutdown the jupyterhub process but then kubernetes will notice that the hub has stopped running and rush over to restart it.

I think you can see the cloud billing costs broken down by category. (Maybe ask Chris H for a copy or link to the script he uses to export the mybinder.org costs by category. I don't have enough access rights for mybinder.org to be able to look at the bills :-/)

**Comment by lwasser** [comment]
@betatim THANK YOU for this explanation. it's so helpful. So what i'm hearing is that the HUB has an internal DB system that tracks users. And this is SEPARATE from kubernetes. So when we add users to our YAML file it initially populates both the hub DB and authentication via Kubernetes or google cloud? <i may not understand this part enuf to use the right words>. 

But the long story short is that if we are using kubernetes, we should NOT use the hub admin interface to manage users. but we can clean it up when we remove users. 

At the end of the day we will want to shut down the hub, and add /remove users via the YAML files + the google cloud shell interface 

I'll totally bug chris about cost tracking. i hadn't thought about that. THANK YOU so much for the help here!! i can now add a bit more about maintenance to our docs.

**Comment by lwasser** [comment]
ok great -- closing this as i added documentation in #217  Thank you again Tim!! :)
