### ISSUE TITLE
Monitoring to see what is going on

### ISSUE THREAD

**Issue by betatim** [earthlab/hub-ops#26]
Get started on collecting data to monitor via Prometheus and then displaying it via Grafana. The basics seem to be up and running: https://grafana.earthlab.wtte.ch/d/wqCsGavik/hub-monitoring?refresh=1m&orgId=1

@lwasser when you get back could you create two new domains:
* grafana.hub.earthdatascience.org
* prometheus.hub.earthdatascience.org
they should both point to the same IP as hub.earthdatascience.org does. Once we have that the dashboard can be at grafana.hub.earthdatascience.org

* [ ] can grafana remain public? If no secure it
* [ ] get Leah setup with git-crypt for the secrets
* [ ] what are useful things to show in grafana
* [ ] docs docs docs

**Comment by lwasser** [comment]
ok. i just tried to set this up @betatim ... it will take some time to propogate but both url's are there. i'm a bit confused as to what happens when several subdomains are associated with the same IP... but let's see how this all works. Question - where will this ultimately sit? is this IP from google cloud? or is this your server?

**Comment by lwasser** [comment]
<img width="894" alt="screen shot 2018-07-03 at 2 45 18 pm" src="https://user-images.githubusercontent.com/7649194/42243795-bfbf8ab8-7ecf-11e8-9661-e24f44f2707c.png">

something is happening but i'm getting security issues. not sure what is up with this but also since i don't understand how this is setup on your end tim i can't fix it :) let me know what you need!!

**Comment by betatim** [comment]
I don't think there is any downside to having the same IP for many (sub)domains. Because prometheus and grafana and jupyterhub all want to listen on port 80 we can't have them all on the same domain. Kubernetes does its magic to allow us to have different hostnames but only one IP.

Grafana and prometheus are running on the same cluster as the hubs themselves.

For the security warnings to go away I need to configure the cluster to use the new domain name you just setup. Just used one of my domains to get around the chicken and egg problem of should I first make it work and then ask Leah to setup a domain, or first ask for a domain and then make it work.
