### ISSUE TITLE
How do students add big data files?

### ISSUE THREAD

**Issue by betatim** [earthlab/hub-ops#63]
What is the user story for adding (large) files to a user's home directory?

This might also be connected to #62 as a way to download data.

One option might be https://docs.syncthing.net/

**Comment by lwasser** [comment]
Currently uploading files is problematic!
1. When a student initiates an upload it's hard to know if the hub is doing anything.
2. the upload seems to be VERY very slow. 

So i have a few students who have said it takes maybe 30 minutes to and hour and it still doesn't upload. i am going to work on how to replicate this issue since i know what data they are using but uploading files right now is not ideal.

**Comment by betatim** [comment]
Could you find out what kind of network connection they had when they were trying to upload the files and how big the files are? To learn about their network connection ask them to visit fast.com, wait for it to be done, click "more info" and take a screenshot. Just to know what the connectivity in general was like.

One way around this problem (for files that aren't behind a login/need to be requested) is to download them directly to the hub. Maybe the best way to do that is to add a little helper to `earthpy` like `earthpy.download('http://example.com/cool/data/is/big/data.zip')`?

The lack of feedback is related to  #137.
