### ISSUE TITLE
How to encrypt secrets

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#88]
Ok @betatim i think i understand this process (i hope) BUT currently i'm not sure how to

1. encrypt my secret file so it's truly secret. Can we add that to the docs safely OR locally somehow document it?
2. once i push things to the repo - should the new hub build? or do i have to run things at the command line as well?

Thank you!
Leah

**Comment by betatim** [comment]
There is a PR up now that documents how to share the key and how to use it.

Once it is setup it should be obvious how it works. The files in `secrets/` will "as by magic" be plain text readable to you on your laptop. It happens because of the instructions in `.gitattributes` which tells git to use `git-crypt` when checking out files to "filter" the ones in `secrets/`, in this case the filtering undoes the encryption.

**Comment by betatim** [comment]
If you setup everything right then merging a PR will be all that is needed to get your new hub to start up.
